# Stress Perception and Work-life Balnce

## Summary: 
**df_wb**: Lifestyle_and_Wellbeing_Data
**df_index**: Positive Experience Index & Negative Experience Index
**df_ab**: Absenteeism (global data)

## Lifestyle_and_Wellbeing_Data

#### About this file

This dataset contains the survey responses from www.Authentic-Happiness.com.
There are 24 attributes describing how we live our lives, including a calculated field, the Work_Life_Balance_Score.

The Work-Life Balance survey evaluates how we thrive in both your professional and personal lives: it reflects how well you shape your lifestyle, habits and behaviors to maximize your overall life satisfaction along the following five dimensions:

1.**Healthy body**, reflecting your fitness and healthy habits;

2.**Healthy mind**, indicating how well you embrace positive emotions;

3.**Expertise**, measuring the ability to grow your expertise and achieve something unique;

4.**Connection**, assessing the strength of your social network and your inclination to discover the world;

5.**Meaning**, evaluating your compassion, generosity and how much 'you are living the life of your dream'.

#### Columns

**Timestamp**: Date when survey was completed

**FRUITS_VEGGIES**: HOW MANY FRUITS OR VEGETABLES DO YOU EAT EVERYDAY?

**DAILY_STRESS**: HOW MUCH STRESS DO YOU TYPICALLY EXPERIENCE EVERYDAY?
► At work or at home, due to the environment (noise, pollution, insecurity...), your co-workers or boss, or because of tragic events such as divorce, job loss, serious illness, loss of family or friends,... ► In average over 12 months.
Score fom 0 (Not much stress) to 5 (A lot of stress)

**PLACES_VISITED**: HOW MANY NEW PLACES DO YOU VISIT?

**CORE_CIRCLE**: HOW MANY PEOPLE ARE VERY CLOSE TO YOU?

**SUPPORTING_OTHERS**: HOW MANY PEOPLE DO YOU HELP ACHIEVE A BETTER LIFE?

**SOCIAL_NETWORK**: WITH HOW MANY PEOPLE DO YOU INTERACT WITH DURING A TYPICAL DAY?

**ACHIEVEMENT**: HOW MANY REMARKABLE ACHIEVEMENTS ARE YOU PROUD OF?

**DONATION**: HOW MANY TIMES DO YOU DONATE YOUR TIME OR MONEY TO GOOD CAUSES?

**BMI_RANGE**: WHAT IS YOUR BODY MASS INDEX (BMI) RANGE?

**TODO_COMPLETED**: HOW WELL DO YOU COMPLETE YOUR WEEKLY TO-DO LISTS?

**FLOW**: IN A TYPICAL DAY, HOW MANY HOURS DO YOU EXPERIENCE "FLOW"?
► 'Flow' is defined as the mental state, in which you are fully immersed in performing an activity. You then experience a feeling of energized focus, full involvement, and enjoyment in the process of this activity. ► Watch the youtube video from Mihaly Csikszentmihalyi "Flow, the secret to happiness"

**DAILY_STEPS**: HOW MANY STEPS (IN THOUSANDS) DO YOU TYPICALLY WALK EVERYDAY?

**LIVE_VISION**: FOR HOW MANY YEARS AHEAD IS YOUR LIFE VISION VERY CLEAR FOR?

**SLEEP_HOURS**: ABOUT HOW LONG DO YOU TYPICALLY SLEEP?
► Over the course of a typical working week, including weekend (Hours per night)

**LOST_VACATION**: HOW MANY DAYS OF VACATION DO YOU TYPICALLY LOSE EVERY YEAR ?

**DAILY_SHOUTING**: HOW OFTEN DO YOU SHOUT OR SULK AT SOMEBODY?
► In a typical week. ► Expressing your negative emotions in an active or passive manner. (Times per week)

**SUFFICIENT_INCOME**: HOW SUFFICIENT IS YOUR INCOME TO COVER BASIC LIFE EXPENSES?

**PERSONAL_AWARDS**: HOW MANY RECOGNITIONS HAVE YOU RECEIVED IN YOUR LIFE?

**TIME_FOR_PASSION**: HOW MANY HOURS DO YOU SPEND EVERYDAY DOING WHAT YOU ARE PASSIONATE ABOUT?

**WEEKLY_MEDITATION**: IN A TYPICAL WEEK, HOW MANY TIMES DO YOU HAVE THE OPPORTUNITY TO THINK ABOUT YOURSELF?
► Include meditation, praying and relaxation activities such as fitness, walking in a park or lunch breaks.

**AGE**: AGE GROUPS

**GENDER**: MALE OR FEMALE

**WORK_LIFE_BALANCE_SCORE**: SCORE CALCULATED BY AH.COM ALGORITHM AND REPORTED TO USER IN THE FIRST REPORT

Link to the form: https://docs.google.com/forms/d/e/1FAIpQLSdRbkamYgEkFvlA0605CZSe_8-clPy3lg_Fig6Eard5syho2w/viewform

In [1]:
pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
path = "Wellbeing_and_lifestyle_data_Kaggle.csv"
df_wb = pd.read_csv(path)
pd.set_option('display.max_columns', None)
df_wb

,Timestamp,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,FLOW,DAILY_STEPS,LIVE_VISION,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
0,7/7/15,3,2,2,5,0,5,2,0,1,6,4,5,0,7,5,5,1,4,0,5,36 to 50,Female,609.5
1,7/7/15,2,3,4,3,8,10,5,2,2,5,2,5,5,8,2,2,2,3,2,6,36 to 50,Female,655.6
2,7/7/15,2,3,3,4,4,10,3,2,2,2,2,4,5,8,10,2,2,4,8,3,36 to 50,Female,631.6
3,7/7/15,3,3,10,3,10,7,2,5,2,3,5,5,0,5,7,5,1,5,2,0,51 or more,Female,622.7
4,7/7/15,5,1,3,3,10,4,2,4,2,5,0,5,0,7,0,0,2,8,1,5,51 or more,Female,663.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15967,3/14/21 5:42,3,3,0,4,0,10,0,4,2,8,2,10,7,7,0,1,1,5,2,5,51 or more,Female,644.5
15968,3/14/21 6:30,3,3,6,8,7,4,6,3,1,7,5,6,5,6,0,0,2,10,5,8,21 to 35,Female,714.9
15969,3/14/21 8:35,4,3,0,10,10,8,6,5,1,7,3,5,2,7,0,1,2,10,1,10,21 to 35,Male,716.6
15970,3/14/21 8:43,1,1,10,8,2,7,3,2,1,6,10,1,5,8,7,2,2,1,6,8,21 to 35,Female,682.0
15971,3/14/21 9:03,5,4,0,2,10,10,5,1,2,7,4,1,5,8,5,2,2,1,8,4,21 to 35,Female,651.4